/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "pelobuf_settings.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PelobufSettings, PelobufSettings, AUTO)


PB_BIND(TimeRequest, TimeRequest, AUTO)


PB_BIND(TimeRequest_TimeData, TimeRequest_TimeData, AUTO)


PB_BIND(TimeResponse, TimeResponse, AUTO)


PB_BIND(EnterDFUModeRequest, EnterDFUModeRequest, AUTO)


PB_BIND(EnterDFUModeResponse, EnterDFUModeResponse, AUTO)



