/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "pelobuf_info.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PelobufInfo, PelobufInfo, AUTO)


PB_BIND(PlatformRequest, PlatformRequest, AUTO)


PB_BIND(PlatformResponse, PlatformResponse, AUTO)


PB_BIND(VersionInfoRequest, VersionInfoRequest, AUTO)


PB_BIND(VersionInfoResponse, VersionInfoResponse, AUTO)


PB_BIND(VersionInfoResponse_VersionItem, VersionInfoResponse_VersionItem, AUTO)


PB_BIND(SerialNumberListRequest, SerialNumberListRequest, AUTO)


PB_BIND(SerialNumberListResponse, SerialNumberListResponse, AUTO)


PB_BIND(SerialNumberListResponse_SerialNumber, SerialNumberListResponse_SerialNumber, AUTO)






