/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "pelobuf_bike_metrics.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PelobufBikeMetrics, PelobufBikeMetrics, AUTO)


PB_BIND(WorkoutDataRequest, WorkoutDataRequest, AUTO)


PB_BIND(WorkoutDataResponse, WorkoutDataResponse, AUTO)


PB_BIND(RpmRequest, RpmRequest, AUTO)


PB_BIND(RpmResponse, RpmResponse, AUTO)


PB_BIND(ResistanceRequest, ResistanceRequest, AUTO)


PB_BIND(ResistanceResponse, ResistanceResponse, AUTO)


PB_BIND(PowerRequest, PowerRequest, AUTO)


PB_BIND(PowerResponse, PowerResponse, AUTO)


PB_BIND(LoadCellReadingRequest, LoadCellReadingRequest, AUTO)


PB_BIND(LoadCellReadingResponse, LoadCellReadingResponse, AUTO)


PB_BIND(LoadCellDataRequest, LoadCellDataRequest, AUTO)


PB_BIND(LoadCellDataResponse, LoadCellDataResponse, AUTO)


PB_BIND(StepperMotorDataRequest, StepperMotorDataRequest, AUTO)


PB_BIND(StepperMotorDataResponse, StepperMotorDataResponse, AUTO)


PB_BIND(ResistanceDataRequest, ResistanceDataRequest, AUTO)


PB_BIND(ResistanceDataResponse, ResistanceDataResponse, AUTO)


PB_BIND(EncoderDataRequest, EncoderDataRequest, AUTO)


PB_BIND(EncoderDataResponse, EncoderDataResponse, AUTO)




